version : '3'

networks:
  loki:
   external: true

services:
 eventbusapi:
  image: eventbusapi:dev
  container_name: eventbusapi
  ports:
   - 8083:80
  networks:
   - loki
  logging:
   driver: fluentd
   options:
    fluentd-address: 0.0.0.0:24224


